### ISSUE TITLE
사용자 로그인 API 요청/응답 스펙 재정의 필요

### ISSUE THREAD

**Issue by zhtcks** [cotchan/AlgorithmQuizCurator#18]
# 현재 상태

+ 현재는 아래와 같이 예시로 `status`와 `timestamp`만 내려주는 것으로 작성해놓음

<img width="980" alt="스크린샷 2021-07-15 오후 9 21 46" src="https://user-images.githubusercontent.com/75410527/125787292-83a1a432-91d2-4a77-82d8-b331d1935637.png">

# 수정 요청 사항 1

+ 로그인 성공 시 최소 `accessToken`이 필요하다.

+ 현재 테스트한 바로는 아래와 같이 응답을 내려준다.

1. `apiToken`: 로그인 성공 시 발급받는 인증토큰(JWT)
2. `User Entity` 정보
   + apiToken 값만 가지고 있어도 디코딩을 통해 userEntity 정보를 얻을 수는 있음.  

```json
{
    "success": true,
    "response": {
        "apiToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJuaWNrTmFtZSI6InRlc3QwMDEiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoiYWxnb3JpdGhtX3F1aXpfY3VyYXRvciIsImV4cCI6MTYyNTk5OTMwNCwiaWF0IjoxNjI1OTk1NzA0LCJ1c2VySWQiOiJ6b3JvS2V2aW4iLCJ1c2VyS2V5IjoyM30.EZGn2HExfJvI128TQ-QoWlxNF-V27FBIKLADRo-hasnYLhHf1__1rfAaMeGpGvjE-00MW4h47J5abk50wVifiA",
        "user": {
            "seq": 23,
            "userId": "zoroKevin",
            "nickName": "test001"
        }
    },
    "error": null
}
``` 

# 수정 요청 사항 2

+ 현재 Request Body로는 `id`, `pw`가 되어있지만 일반적으로 인증을 의미하는 단어로 `Principal`과 `Credentials`이라는 단어를 사용. 그러므로 id, pw 필드를 Principal, Credentials 필드로 함이 의미상 더 적절하다고 보임

+ `Principal`: 인증 주체를 의미하는단어로, 일반적으로 User Id가 들어감
+ `Credentials`: 인증 정보를 의미하는 단어로, 일반적으로 User password가 들어감

**Comment by kevin0309** [comment]
# 회의 결과
## 수정 요청 사항 1
- 구현된 기능에 맞추어 API 문서 수정
## 수정 요청 사항 2
- end-point 단에서는 id, pw가 익숙하므로 principal, credenrtials로 사용하지 않기로 정함
- 현상유지!
