### ISSUE TITLE
컴포넌트(Service, Controller 등) 별 return 타입 통합

### ISSUE THREAD

**Issue by zhtcks** [cotchan/AlgorithmQuizCurator#19]
# 안건

+ Controller, Service Layer에서 내려주는 데이터 양식(return value)을 통일한다.
    + 즉, 컨트롤러 메서드, 서비스 메서드에서 내려주는 return value를 통일하자는 얘기

# 의견

+ 단어 정의
  + `Domain Model`: `model` 패키지내에 존재하는 Table에 해당하는 값들로 서버 내 비즈니스 로직의 대상을 의미한다. 
  + `DTO`: REST API 형태로 Client(Front)에 응답을 내려주는 데이터를 의미한다. 이는 Domain Model과 형태가 일치할 수도 있고, 다를 수도 있다.

## 의견1. Service (UserService, ProblemService...)의 return value는 Domain Model
  + 이유: Service는 여러 Controller에서 사용할 수 있다. 그렇기 때문에 특정 Controller의 응답에 맞는 DTO가 아닌 Domain Model 형태로 결과를 내려주고 각 Controller가 Domain Model을 DTO로 변환하는 식으로 사용하는 방식이 좀 더 확장성이 높다.

---

## 의견2. Controller (UserRestController, ProblemRestController...)의 return value는 DTO
  + 이유: Client에게 내려주는 응답 포맷과, 실제 내부 비즈니스로직에 사용되는 도메인 모델은 분리되어야 한다. 도메인 모델을 Controller와 Service에서 모두 응답 데이터로 사용하게 되면 사용자에게 내려주는 응답 포맷 변경이 내부 비즈니스 로직에 영향을 끼칠 수 있다. 
  + Client에게 내려주는 응답 포맷이 바뀌어도 내부 비즈니스 로직에는 영향이 가지 않도록 이 둘을 분리하는 것이 확장성이 높다.

---

## 의견3. 컨트롤러는 RequestBody로 RequestDTO를 받고, ResponseBody로 ResponseDTO를 돌려준다.
  + 의견 1, 2를 이유로 의견3과 같은 형태를 제시함.

+ 예시

```java
//UserRestController.java

//JoinRequest - RequestDTO 의미
//JoinResult - ResponseDTO 의미

@PostMapping
public ApiResult<JoinResult> join(@RequestBody JoinRequest) { 
    //...
}

```

**Comment by kevin0309** [comment]
# 회의 결과
## 의견 1
- 프레임워크와 비즈니스로직을 개념적으로 분리하기 위해 해당 내용 수용
- Service의 리턴형으로 DTO를 사용하지 않음
## 의견 2
- Controller의 리턴형으로 DTO를 사용하나 ApiResult 클래스로 리턴할 DTO를 wrapping 하여 사용하는 것으로 통일
- ApiResult 클래스는 일관성있는 response body 구성을 위해 구현하였으며 아직 손봐야할 부분이 있음 (참고: #23 )
## 의견 3
- 각각 요청/응답에 직접적으로 관여하는 DTO의 클래스명을 각각 Request/Response로 지정하는 것을 수용
- RequestBody에 DTO를 사용하기 위해 Jackson 라이브러리를 사용했음 (참고: #20 )
- ResponseBody에 사용될 DTO는 위의 의견2와 같이 사용
