### ISSUE TITLE
ApiResult 관련 이슈

### ISSUE THREAD

**Issue by kevin0309** [cotchan/AlgorithmQuizCurator#23]
1. 원래 컨트롤러의 리턴 타입이 void인 경우 어떻게 처리해야할지?
2. ApiResult.OK, ApiResult.ERROR 를 동시에 쓰려면 컨트롤러 리턴타입을 ApiResult<?>으로 지정해야 하는데 이대로 사용할것인지?

**Comment by zhtcks** [comment]
## 리턴타입이 없는 경우

+ 함수의 리턴 타입은 `ApiResult<Void>` 로 하고, `ApiResult.OK(null)`을 리턴한다.

```java
//Sample Code

@RestController
public class UserRestController {

    private final UserService userService;

    @Async
    @PostMapping("join")
    publicApiResult<Void> joinProcess(@RequestBody JoinRequest newUser) {
        userService.join(newUser);
        returnApiResult.OK(null);
    }
}
```

**Comment by zhtcks** [comment]
## ApiResult<?>

+ GlobalExceptionHandler를 사용해서 예외처리를 전부하므로 Controller에서는 ApiResult.OK만 리턴한다.
+ 리턴형의 결과를 명확히 명시하기 위해 ? 는 사용하지 않는다.
