### ISSUE TITLE
[프로젝트 init] 도메인 모델 생성 및 Repository 생성

### ISSUE THREAD

**Issue by zhtcks** [cotchan/AlgorithmQuizCurator#3]

**Comment by cotchan** [comment]
+ User, Quiz 등 테이블에 대한 도메인 모델 만들기

**Comment by zhtcks** [comment]
# 작업 내용

+ 테이블에 해당하는 Domain Model 생성 및 Repository 생성

# 참고 URL

+ [[JAVA] Lombok이란? Lombok 적용하는 방법](https://dololak.tistory.com/783)
+ [sb2) Lombok 설치(with Intellij & Gradle)](https://cotchan.github.io/posts/sb2-setup-lombok/)
+ [JPA) 연관관계 매핑3. 다대일[N:1]](https://cotchan.github.io/posts/jpa-association-mapping-nto1/)
+ [JPA PK 매핑](https://ultrakain.gitbooks.io/jpa/content/chapter4/chapter4.6.html)
+ [JPA 사용법 (JpaRepository)](https://jobc.tistory.com/120)
+ [Spring Data JPA - Reference Documentation
](https://docs.spring.io/spring-data/jpa/docs/1.10.1.RELEASE/reference/html/#jpa.query-methods.at-query)
