### ISSUE TITLE
APIs for sign up make 401 error

### ISSUE THREAD

**Issue by pithesun** [cotchan/AlgorithmQuizCurator#61]
ERROR: Failed to load resource: the server responded with a status of 401 (Unauthorized)

api/user/dup-check-by-userId/abcd1234 401 (Unauthorized)
api/user/verify-questions
api/user/dup-check-by-nickname/ab

api/user/join:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

```javascript
export function joinUser(dataToSubmit) {
  const request = axios
    .post("/api/user/join",  dataToSubmit, {
      headers: {"Content-Type": `application/json`},
    })
    .then((response) => response.data);
  return {
    type: JOIN_USER,
    payload: request,
  };
}
```

```javascript
 let body = {
      id,
      pw,
      pw_confirm: pw,
      nickname,
      verify_question,
      verify_answer,
    };

    dispatch(joinUser(body)).then((response) => {
      if (response.payload.joinSuccess) {
        alert("회원가입 성공");
        props.history.push("/");
      } else {
        // alert("회원가입 실패");
      }
    });
```

**Comment by kevin0309** [comment]
### api/user/join:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
회원가입 시 몇가지 제약사항이 있는데 API문서에 남기는걸 깜빡했네요
일단 여기서 확인해주세요
https://github.com/cotchan/AlgorithmQuizCurator/issues/8#issuecomment-877006972
API 문서에도 남기도록 하겠습니다

**Comment by kevin0309** [comment]
### api/user/dup-check-by-userId/abcd1234 401 (Unauthorized)
요거는 제쪽에서 확인이 안되네요
제쪽에서는 정상적으로 작동 확인했습니다
![image](https://user-images.githubusercontent.com/32089450/128673303-aa47d61b-3641-4c8f-9154-c8ab39c9bf51.png)

**Comment by kevin0309** [comment]
수정사항 반영하여 API 문서에도 작성했습니다
401 에러는 다시 한번 확인 부탁드려요~
